/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void guiDraw(PApplet appc, GWinData data) { //_CODE_:gui:302821:
  appc.background(230);
} //_CODE_:gui:302821:

public void alliesChanged(GCustomSlider source, GEvent event) { //_CODE_:allies:364778:
  numAlliesChange();
} //_CODE_:allies:364778:

public void restartButClicked(GButton source, GEvent event) { //_CODE_:restartBut:913231:
  flagPos.set(300, 100);
} //_CODE_:restartBut:913231:

public void pauseButClicked(GButton source, GEvent event) { //_CODE_:pauseBut:609814:
  if (pause == false){
    pause = true;
  }
  else{
    pause = false;
  }
} //_CODE_:pauseBut:609814:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  gui = GWindow.getWindow(this, "GUI", 0, 0, 240, 120, JAVA2D);
  gui.noLoop();
  gui.setActionOnClose(G4P.KEEP_OPEN);
  gui.addDrawHandler(this, "guiDraw");
  allies = new GCustomSlider(gui, 30, 40, 100, 40, "grey_blue");
  allies.setShowValue(true);
  allies.setShowLimits(true);
  allies.setLimits(1, 1, 20);
  allies.setNumberFormat(G4P.INTEGER, 0);
  allies.setOpaque(false);
  allies.addEventHandler(this, "alliesChanged");
  alliesLabel = new GLabel(gui, 30, 20, 80, 20);
  alliesLabel.setText("Allies");
  alliesLabel.setOpaque(false);
  restartBut = new GButton(gui, 140, 20, 80, 30);
  restartBut.setText("Restart");
  restartBut.setLocalColorScheme(GCScheme.RED_SCHEME);
  restartBut.addEventHandler(this, "restartButClicked");
  pauseBut = new GButton(gui, 140, 70, 80, 30);
  pauseBut.setText("Pause");
  pauseBut.addEventHandler(this, "pauseButClicked");
  gui.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow gui;
GCustomSlider allies; 
GLabel alliesLabel; 
GButton restartBut; 
GButton pauseBut; 
