/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void guiDraw(PApplet appc, GWinData data) { //_CODE_:gui:660207:
  appc.background(230);
} //_CODE_:gui:660207:

public void numAllies(GCustomSlider source, GEvent event) { //_CODE_:allies:934943:
  println("Allies - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:allies:934943:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  gui = GWindow.getWindow(this, "GUI", 100, 200, 240, 120, JAVA2D);
  gui.noLoop();
  gui.setActionOnClose(G4P.KEEP_OPEN);
  gui.addDrawHandler(this, "guiDraw");
  allies = new GCustomSlider(gui, 70, 40, 100, 40, "grey_blue");
  allies.setLimits(10, 1, 20);
  allies.setNumberFormat(G4P.INTEGER, 0);
  allies.setOpaque(false);
  allies.addEventHandler(this, "numAllies");
  alliesLabel = new GLabel(gui, 70, 20, 80, 20);
  alliesLabel.setText("Allies");
  alliesLabel.setOpaque(false);
  gui.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow gui;
GCustomSlider allies; 
GLabel alliesLabel; 
